all: test1 test2 test3
test1:test1.cc
	g++ -std=c++11 -o test1 test1.cc -ljsoncpp
test2:test2.cc
	g++ -std=c++11 -o test2 test2.cc -ljsoncpp
test3:test3.cc
	g++ -std=c++11 -o test3 test3.cc -ljsoncpp
clean:
	rm -f test1 test2 test3